-- Create enums
CREATE TYPE "RoleName" AS ENUM ('admin', 'financeiro', 'auditor');
CREATE TYPE "InvoiceStatus" AS ENUM ('received', 'parsing', 'parsed', 'classified', 'review_required', 'allocated', 'reconciled', 'error');
CREATE TYPE "ReviewStatus" AS ENUM ('pending', 'in_review', 'resolved');

-- Basic tables
CREATE TABLE "User" (
  "id" TEXT PRIMARY KEY,
  "email" TEXT NOT NULL UNIQUE,
  "name" TEXT NOT NULL,
  "passwordHash" TEXT NOT NULL,
  "role" "RoleName" NOT NULL,
  "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE "Role" (
  "id" TEXT PRIMARY KEY,
  "name" "RoleName" NOT NULL UNIQUE,
  "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE "CostCenter" (
  "id" TEXT PRIMARY KEY,
  "code" TEXT NOT NULL UNIQUE,
  "name" TEXT NOT NULL,
  "description" TEXT,
  "area" TEXT,
  "status" TEXT NOT NULL DEFAULT 'active',
  "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE "Project" (
  "id" TEXT PRIMARY KEY,
  "code" TEXT NOT NULL UNIQUE,
  "name" TEXT NOT NULL,
  "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE "Vendor" (
  "id" TEXT PRIMARY KEY,
  "name" TEXT NOT NULL UNIQUE,
  "domain" TEXT,
  "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE "VendorAlias" (
  "id" TEXT PRIMARY KEY,
  "alias" TEXT NOT NULL,
  "vendorId" TEXT NOT NULL REFERENCES "Vendor"("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE TABLE "Invoice" (
  "id" TEXT PRIMARY KEY,
  "externalId" TEXT,
  "vendorId" TEXT REFERENCES "Vendor"("id") ON DELETE SET NULL ON UPDATE CASCADE,
  "competency" TIMESTAMP,
  "amount" DECIMAL(14,2) NOT NULL,
  "currency" TEXT NOT NULL DEFAULT 'USD',
  "status" "InvoiceStatus" NOT NULL DEFAULT 'received',
  "sourceType" TEXT NOT NULL,
  "confidence" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "rawText" TEXT,
  "rawJson" JSONB,
  "costCenterCode" TEXT,
  "suggestedAllocation" JSONB,
  "processedAt" TIMESTAMP,
  "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE "InvoiceItem" (
  "id" TEXT PRIMARY KEY,
  "invoiceId" TEXT NOT NULL REFERENCES "Invoice"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  "description" TEXT NOT NULL,
  "quantity" DOUBLE PRECISION,
  "unitPrice" DECIMAL(14,2),
  "total" DECIMAL(14,2)
);
CREATE TABLE "InvoiceSource" ("id" TEXT PRIMARY KEY, "invoiceId" TEXT, "sourceType" TEXT NOT NULL, "externalId" TEXT, "processingStep" TEXT NOT NULL, "rawJson" JSONB, "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "EmailMessage" ("id" TEXT PRIMARY KEY, "messageId" TEXT NOT NULL UNIQUE, "fromEmail" TEXT NOT NULL, "toEmail" TEXT NOT NULL, "subject" TEXT NOT NULL, "sentAt" TIMESTAMP NOT NULL, "snippet" TEXT, "body" TEXT, "status" TEXT NOT NULL DEFAULT 'received', "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "EmailAttachment" ("id" TEXT PRIMARY KEY, "emailMessageId" TEXT NOT NULL REFERENCES "EmailMessage"("id") ON DELETE RESTRICT ON UPDATE CASCADE, "fileName" TEXT NOT NULL, "mimeType" TEXT NOT NULL, "path" TEXT NOT NULL, "size" INTEGER NOT NULL);
CREATE TABLE "UploadedFile" ("id" TEXT PRIMARY KEY, "fileName" TEXT NOT NULL, "path" TEXT NOT NULL, "mimeType" TEXT NOT NULL, "sourceType" TEXT NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "ExtractionResult" ("id" TEXT PRIMARY KEY, "invoiceId" TEXT NOT NULL REFERENCES "Invoice"("id") ON DELETE RESTRICT ON UPDATE CASCADE, "provider" TEXT NOT NULL, "confidence" DOUBLE PRECISION NOT NULL, "rawJson" JSONB NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "OCRResult" ("id" TEXT PRIMARY KEY, "invoiceId" TEXT NOT NULL REFERENCES "Invoice"("id") ON DELETE RESTRICT ON UPDATE CASCADE, "provider" TEXT NOT NULL, "confidence" DOUBLE PRECISION NOT NULL, "rawText" TEXT NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "AIAnalysis" ("id" TEXT PRIMARY KEY, "invoiceId" TEXT NOT NULL REFERENCES "Invoice"("id") ON DELETE RESTRICT ON UPDATE CASCADE, "provider" TEXT NOT NULL, "confidence" DOUBLE PRECISION NOT NULL, "justification" TEXT NOT NULL, "structuredData" JSONB NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "ClassificationRule" ("id" TEXT PRIMARY KEY, "name" TEXT NOT NULL, "ruleType" TEXT NOT NULL, "condition" TEXT NOT NULL, "action" JSONB NOT NULL, "confidenceBoost" DOUBLE PRECISION NOT NULL DEFAULT 0, "requireReview" BOOLEAN NOT NULL DEFAULT false, "active" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "AllocationRule" ("id" TEXT PRIMARY KEY, "name" TEXT NOT NULL, "ruleType" TEXT NOT NULL, "condition" TEXT NOT NULL, "allocation" JSONB NOT NULL, "active" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "AllocationResult" ("id" TEXT PRIMARY KEY, "invoiceId" TEXT NOT NULL REFERENCES "Invoice"("id") ON DELETE RESTRICT ON UPDATE CASCADE, "ruleId" TEXT, "allocationType" TEXT NOT NULL, "split" JSONB NOT NULL, "decisionSource" TEXT NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Payment" ("id" TEXT PRIMARY KEY, "vendorName" TEXT NOT NULL, "amount" DECIMAL(14,2) NOT NULL, "currency" TEXT NOT NULL, "paidAt" TIMESTAMP NOT NULL, "reference" TEXT, "source" TEXT NOT NULL, "rawJson" JSONB, "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Reconciliation" ("id" TEXT PRIMARY KEY, "invoiceId" TEXT NOT NULL REFERENCES "Invoice"("id") ON DELETE RESTRICT ON UPDATE CASCADE, "paymentId" TEXT NOT NULL REFERENCES "Payment"("id") ON DELETE RESTRICT ON UPDATE CASCADE, "score" DOUBLE PRECISION NOT NULL, "status" TEXT NOT NULL, "notes" TEXT, "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "ReviewTask" ("id" TEXT PRIMARY KEY, "invoiceId" TEXT NOT NULL REFERENCES "Invoice"("id") ON DELETE RESTRICT ON UPDATE CASCADE, "status" "ReviewStatus" NOT NULL DEFAULT 'pending', "reason" TEXT NOT NULL, "assignedTo" TEXT, "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "AuditLog" ("id" TEXT PRIMARY KEY, "userId" TEXT REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE, "entityType" TEXT NOT NULL, "entityId" TEXT NOT NULL, "action" TEXT NOT NULL, "details" JSONB, "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Setting" ("id" TEXT PRIMARY KEY, "key" TEXT NOT NULL UNIQUE, "value" TEXT NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "JobExecution" ("id" TEXT PRIMARY KEY, "jobName" TEXT NOT NULL, "status" TEXT NOT NULL, "attempts" INTEGER NOT NULL DEFAULT 0, "errorMessage" TEXT, "startedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "endedAt" TIMESTAMP);
